{ config, lib, modulesPath, ... }:

{
  # This file should be generated by command, do not edit manually.
  # Replace this file with:
  #   nixos-generate-config --show-hardware-config > hardware.nix
  #
  # The content above is a minimal placeholder to allow the template to
  # evaluate. Without it you will not have filesystem info, kernel modules,
  # or boot device configuration specific to your machine.
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee";
    fsType = "ext4";
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
