name: detect-package-changes

on:
  push:
    paths: [flake.lock, sources.json]

permissions:
  contents: read
  issues: write

jobs:
  diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 2

      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ github.token }}

      - name: Detect package changes
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          body=$(python3 scripts/detect-package-changes.py)
          if [ -n "$body" ]; then
            title="[bot][$(date +%F)] Update Report"
            gh issue create --label package-changes --title "$title" --body "$body"
          fi
